#!/bin/bash

function	install::vbox::arch()
{
	sudo pacman -Syu --noconfirm virtualbox-guest-utils
	sudo systemctl enable --now vboxservice
	sudo modprobe -a vboxguest vboxsf vboxvideo
}

## BINDED FUNCTION

function	install::vbox()
{
	case "${OS_ID}" in
		"arch") install::vbox::arch ;;
		*) print::warn "${OS_ID} not implemented yet" ;;
	esac
}

# Start
function	module::start()
{
	local	base="${BASH_SOURCE[0]?}"

	# remove filename
	base="${base/install/}"
	# if base dir is relative, suffix PWD to base
	if [[ ${base} =~ ^\./.*$ ]]; then
		base="${PWD}/${base}"
	fi
	# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
	if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
		source "${base}../../dot"

		## BINDED FUNCTION
		module::install "${MOD_NAME}"
	fi
}

module::start
