#!/bin/bash

function	install::vbox::arch()
{
	sudo pacman -Syu virtualbox-guest-utils
	sudo modprobe -a vboxguest vboxsf vboxvideo
}

function	install::vbox()
{
	case "${OS_ID}" in
		"arch") install::vbox::arch ;;
		*) print::warn "${OS_ID} not implemented yet" ;;
	esac
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "vbox/install" ]; then
		source ../run
	else
		source ./run
	fi
	install::vbox
fi
