#!/bin/bash

function ask()
{
	local message=$1
	local default=$2
	[ -z ${2} ] && local default="NULL"
	local choice=""
	local loop=1

	if [ ${default} == "y" ]; then
		printf "${message} (Y/n) "
	elif [ ${default} == "n" ]; then
		printf "${message} (y/N) "
	else
		printf "${message} (y/n) "
	fi

	read -n 1 choice
	printf "\n"
	choice=${choice,,}
	if [ ${choice} != "y" ] && [ ${choice} != "n" ]; then
		[ ${default} == "y" ] && return 1
		[ ${default} == "n" ] && return 0
	fi
	[ ${choice} == "y" ] && return 1
	[ ${choice} == "n" ] && return 0
}

source .config

function main()
{
	source bash/install
	source gdb/install
	source vim/install

	install_bash_config
	install_gdb_config
	install_vim_config
}

if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	main
fi
