#!/bin/bash

PATH_CONFIG=$(realpath ${BASH_SOURCE[0]})
DIR_BASE=${PATH_CONFIG%/*}
source ./.config

function	setup::prepare()
{
	[ -f "${DOT_INSTALL_DIR}" ] && rm -f "${DOT_INSTALL_DIR}"
	[ ! -d "${DOT_INSTALL_DIR}" ] && mkdir -p "${DOT_INSTALL_DIR}"
	[ -d "${DOT_INSTALL_DIR}/dot_files" ] && rm -rf "${DOT_INSTALL_DIR}/dot_files"
}

function	setup::install()
{
	cp -r "${PWD}" "${DOT_INSTALL_DIR}"
	[ -L "${DOT_INSTALL_DIR}/dot" ] && rm "${DOT_INSTALL_DIR}/dot"
	ln -s "${DOT_INSTALL_DIR}/dot_files/dot" "${DOT_INSTALL_DIR}/dot"
}

setup::prepare
setup::install

"${DOT_INSTALL_DIR}/dot" -f
