#!/bin/bash

function	install::vscode()
{
	utils::move_dir "${MOD_FILE_DIR}" "${TARGET_DIR}" y
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../dot
	elif [ "${0}" -ef "vscode/install" ]; then
		source ../dot
	else
		source ./dot
	fi
	install::vscode
	post::install::vscode
fi
