#!/bin/bash

function	install::i3::package()
{
	local to_install=""

	if [ ! "$(type -P i3)" ]; then
		to_install+="i3-wm "
	fi

	for package in ${I3_PACKAGE_PAC[@]}; do
		if [ ! "$(type -P i3)" ]; then
			to_install+="${package} "
		fi
	done
	pacman -Syu --noconfirm "${to_install}"
	to_install=""
	for package in ${I3_PACKAGE_YAY[@]}; do
		if [ ! "$(type -P i3)" ]; then
			to_install+="${package} "
			yay -S --noconfirm ${package}
		fi
	done
}

function	install::i3()
{
	[ ${UID} -ne 0 ] && { print::erro "Run as root."; exit 123; }
	pacman -Syu --noconfirm
	yay -Syu --noconfirm
	install::i3::package
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "i3/install" ]; then
		source ../run
	else
		source ./run
	fi
	install::i3
fi
