#!/bin/bash

function	install_vim_config()
{
	local	do_install='1'

	if [ -z "${FORCE_REPLACE}" ] && [ -f ${HOME}/.vimrc ]; then
		ask "file ${HOME}/.vimrc exists, do you wan't to overwrite it " "y"
		[ "$?" == "0" ] && do_install='0'
	fi
	if [ "${do_install}" == "1" ]; then
		cp ${VIMRC_PATH} ${HOME}/.vimrc
		p_done ".vimrc configuration done."
	else
		p_done "vim configuration skiped." 1
	fi
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" != "./vim/install" ]; then
		printf "launch scripts from rc_files (./vim/install)\n"
	fi
	source installer
	install_vim_config
fi
