#!/bin/bash

function	install_tmux()
{
	[ "${OS_ID}" == "termux" -o -z "${OD_ID}" ] \
	&& move_if_file_exist ${PATH_TMUXRC_FILE_IN} ${PATH_TMUXRC_FILE_OUT}
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "tmux/install" ]; then
		source ../run
	else
		source ./run
	fi
	install_tmux
	post_install_tmux
fi
