#!/bin/bash

function	install::tmux()
{
	[ "${OS_ID}" == "termux" -o -z "${OS_ID}" ] \
	&& utils::move_file ${PATH_TMUXRC_FILE_IN} ${PATH_TMUXRC_FILE_OUT}
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "tmux/install" ]; then
		source ../run
	else
		source ./run
	fi
	install::tmux
	post::install::tmux
fi
