#!/bin/bash

function install_gdb_config()
{
	local	do_install='1'

	if [ -z "${FORCE_REPLACE}" ] && [ -f ${HOME}/.gdbinit ]; then
		ask "file ${HOME}/.gdbinit exists, do you wan't to overwrite it " "y"
		if [ "$?" == "0" ]; then
			do_install='0'
			p_done "gdb configuration skiped." 1
		fi
	fi
	if [ "${do_install}" -eq 1 ]; then
		cp ${GDBINIT_PATH} "${HOME}/.gdbinit"
		p_done "gdb configuration done."
	fi
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" != "./gdb/install" ]; then
		printf "launch scripts from rc_files (./gdb/install)\n"
	fi
	source installer
	install_gdb_config
fi
