#!/bin/bash

## BINDED FUNCTION

function	pre::install::profile()
{
	utils::mkdir "${TARGET_DIR}"
}

function	install::profile()
{
	utils::move_dir "${MOD_FILE_DIR}" "${TARGET_DIR}" y
}

function	post::install::profile()
{
	log::warn "to make effect you have to ${RED}relog${RST} the current user" 1
}

# Start
function	module::start()
{
	local	base="${BASH_SOURCE[0]?}"

	# remove filename
	base="${base/install/}"
	# if base dir is relative, suffix PWD to base
	if [[ ${base} =~ ^\./.*$ ]]; then
		base="${PWD}/${base}"
	fi
	# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
	if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
		source "${base}../../dot"

		## BINDED FUNCTION
		module::install "${MOD_NAME}"
	fi
}

module::start
