#!/bin/bash

## BINDED FUNCTION

function	pre::install::gtk3()
{
	utils::mkdir "${TARGET_DIR}"
}

function	install::gtk3()
{
	local	is_installed

	utils::move_dir "${MOD_FILE_DIR}" "${TARGET_DIR}" y
	pacman -Qi fluent-gtk-theme-git >/dev/null && is_installed=1 || is_installed=0
	if [ "${is_installed}" == "0" ]; then
		yay -Syu fluent-gtk-theme-git
	fi
	pacman -Qi fluent-icon-theme-git >/dev/null && is_installed=1 || is_installed=0
	if [ "${is_installed}" == "0" ]; then
		yay -Syu fluent-icon-theme-git
	fi
}

# Start
function	module::start()
{
	local	base="${BASH_SOURCE[0]?}"

	# remove filename
	base="${base/install/}"
	# if base dir is relative, suffix PWD to base
	if [[ ${base} =~ ^\./.*$ ]]; then
		base="${PWD}/${base}"
	fi
	# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
	if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
		source "${base}../../dot"

		## BINDED FUNCTION
		module::install "${MOD_NAME}"
	fi
}

module::start
