#!/bin/bash

function install_batcat_config()
{
	local	batcat_dir=$(batcat --config-dir)
	local	do_install='1'

	[ ! -d "${batcat_dir}" ] && mkdir ${batcat_dir}
	if [ -z "${FORCE_REPLACE}" ] && [ -f "${batcat_dir}/config" ]; then
		ask "file ${batcat_dir}/config exists, do you wan't to overwrite it " "y"
		if [ "$?" == "0" ]; then
			do_install='0'
			p_done "batcat configuration skiped." 1
		fi
	fi
	if [ "${do_install}" -eq "1" ]; then
		cp ${BATCAT_CONF_PATH} ${batcat_dir}/config
		p_done "batcat configuration done."
	fi
}

if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "batcat/install" ]; then
		source installer
	else
		source ../installer
	fi
	install_batcat_config
fi
