#!/bin/bash

## BINDED FUNCTION

# function	pre::install::mimetype()
# {
# 	utils::mkdir "${TARGET_DIR}"
# }

function	install::mimetype()
{
	xdg-mime default "${FILE_EXPLORER}.desktop" application/x-directory
	xdg-mime default "${FILE_EXPLORER}.desktop" inode/directory
}

# Start
function	module::start()
{
	local	base="${BASH_SOURCE[0]?}"

	# remove filename
	base="${base/install/}"
	# if base dir is relative, suffix PWD to base
	if [[ ${base} =~ ^\./.*$ ]]; then
		base="${PWD}/${base}"
	fi
	# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
	if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
		source "${base}../../dot"

		## BINDED FUNCTION
		module::install "${MOD_NAME}"
	fi
}

module::start
