#!/bin/bash

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> Bash Color

# BEG_ESC='\001'
# END_ESC='\002'

green="${BEG_ESC}\e[32m${END_ESC}"
red="${BEG_ESC}\e[31m${END_ESC}"
yellow="${BEG_ESC}\e[33m${END_ESC}"
blue="${BEG_ESC}\e[34m${END_ESC}"
orange="${BEG_ESC}\e[38;5;208m${END_ESC}"
lgreen="${BEG_ESC}\e[92m${END_ESC}"
lyellow="${BEG_ESC}\e[93m${END_ESC}"
lblue="${BEG_ESC}\e[94m${END_ESC}"
lmagenta="${BEG_ESC}\e[95m${END_ESC}"
lcyan="${BEG_ESC}\e[96m${END_ESC}"
blink_red="${BEG_ESC}\033[05;31m${END_ESC}"
restore="${BEG_ESC}\033[0m${END_ESC}"
reset="${BEG_ESC}\e[0m${END_ESC}"

P_INFO="${lcyan}[INFO]${reset}"
P_WARN="${orange}[WARN]${reset}"
P_QUES="${blue}[QUE?]${reset}"
P_PASS="${green}[PASS]${reset}"
P_FAIL="${red}[FAIL]${reset}"
P_ERRO="${red}[ERRO]${reset}"

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#> print helper

# remove colors
function	p_remove_colors()
{
	P_INFO="[INFO]"
	P_WARN="[WARN]"
	P_QUES="[QUE?]"
	P_PASS="[PASS]"
	P_FAIL="[FAIL]"
	P_ERRO="[ERRO]"
	green=""
	red=""
	yellow=""
	blue=""
	orange=""
	lgreen=""
	lyellow=""
	lblue=""
	lmagenta=""
	lcyan=""
	blink_red=""
	restore=""
	reset=""
}

# print function

## print information
function	p_info()
{
	[ "${DONT_PRINT}" ] && return 0
	printf "${P_INFO} $1${reset}\n"
}

## print warn
function	p_warn()
{
	[ "${DONT_PRINT}" ] && return 0
	printf "${P_WARN} $1${reset}\n"
}

## print question
function	p_ques()
{
	[ "${DONT_PRINT}" ] && return 0
	if [ "${2}" == '1' ]; then
		printf "${P_QUES} $1${reset}\b"
	else
		printf "${P_QUES} $1${reset}\n"
	fi
}

## print success or not
function	p_pass()
{
	[ "${DONT_PRINT}" ] && return 0
	if [ -z ${2} ] || [ ${2} == 0 ]; then
		printf "${P_PASS} $1${reset}\n"
	else
		printf "${P_FAIL} $1${reset}\n"
	fi
}

## print error and quit
function	p_erro()
{
	[ "${DONT_PRINT}" ] && exit 1
	printf "${P_ERRO} $1${reset}\n"
	exit 1
}

## print pause and wait
function	p_pause()
{
	[ "${DONT_PRINT}" ] && return 0
	p_info "Press [Enter] to continue.."
	read readEnterkey
}

#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#==#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
