#!/bin/bash

function	install::vim()
{
	utils::move_file ${PATH_VIMRC_IN} ${PATH_VIMRC_OUT}
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../dot
	elif [ "${0}" -ef "vim/install" ]; then
		source ../dot
	else
		source ./dot
	fi
	install::vim
fi
