#!/bin/bash

## BINDED FUNCTION

function	install::vim::plug()
{
	local	repo_link="https://github.com/${1?}"

	utils::update_repo "${repo_link}" "${PLUG_DIR}"
}

function	install::vim::coc()
{
	local	repo_link="https://github.com/${1?}"

	utils::update_repo "${repo_link}" "${COC_DIR}"
}

function	install::vim::plugins()
{
	log::info "[${ORE}vim${RST}] Installing plugins"

	utils::mkdir "${PLUG_DIR}"
	install::vim::plug "preservim/nerdtree"
	install::vim::plug "vim-airline/vim-airline"
	install::vim::plug "ryanoasis/vim-devicons"
	install::vim::plug "tiagofumo/vim-nerdtree-syntax-highlight"
	install::vim::plug "airblade/vim-gitgutter"
	install::vim::plug "mhinz/vim-signify"
	install::vim::plug "ctrlpvim/ctrlp.vim"
	install::vim::plug "neoclide/coc.nvim"

	# utils::mkdir "${COC_DIR}"
	# install::vim::coc "neoclide/coc-git"
	# install::vim::coc "neoclide/coc-highlight"
	# install::vim::coc "neoclide/coc-json"
	# install::vim::coc "neoclide/coc-python"
	# install::vim::coc "neoclide/coc-tsserver"
	# install::vim::coc "neoclide/coc-yaml"
	# install::vim::coc "josa42/coc-docker"
	# install::vim::coc "josa42/coc-go"
	# install::vim::coc "josa42/coc-lua"
	# install::vim::coc "fannheyward/coc-markdownlint"
	# install::vim::coc "fannheyward/coc-sql"
	# install::vim::coc "fannheyward/coc-xml"
	# install::vim::coc "yaegassy/coc-ansible"
	# install::vim::coc "weirongxu/coc-markdown-preview-enhanced"
	# install::vim::coc "iamcco/coc-vimlsp"
}

function	install::vim()
{
	rm -rf "${TARGET_DIR}/colors"
	utils::move_dir "${MOD_FILE_DIR}" "${TARGET_DIR}" y

	install::vim::plugins
}

# Start
function	module::start()
{
	local	base="${BASH_SOURCE[0]?}"

	# remove filename
	base="${base/install/}"
	# if base dir is relative, suffix PWD to base
	if [[ ${base} =~ ^\./.*$ ]]; then
		base="${PWD}/${base}"
	fi
	# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
	if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
		source "${base}../../dot"

		## BINDED FUNCTION
		module::install "${MOD_NAME}"
	fi
}

module::start
