#!/bin/bash

function	post_install_batcat()
{
	if [ -z $(type -t batcat) ]; then
		p_warn "batcat not installed, skipping"
		return 1
	fi
	p_warn "rebuilding ${orange}batcat${reset} cache"
	batcat cache --build 1>/dev/null
	p_pass "batcat ${green}configured${reset}"
}

function	install_batcat_themes()
{
	for theme in "${BATCAT_DIR_BASE_IN}"/*; do
		if [[ ${theme} =~ .*\.tmTheme ]]; then
			move_if_file_exist ${theme} "${BATCAT_DIR_BASE_OUT}/${theme##*/}"
		fi
	done
}

function	install_batcat_config()
{
	move_if_file_exist ${BATCAT_CONF_FILE_IN} ${BATCAT_CONF_FILE_OUT}
}

function	install_batcat()
{
	if [ -z $(type -t batcat) ]; then
		p_warn "batcat not installed, skipping"
		return 1
	fi
	install_batcat_config
	install_batcat_themes
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "batcat/install" ]; then
		source ../run
	else
		source ./run
	fi
	install_batcat
	post_install_batcat
fi
