#!/bin/bash

function	install_nerdfont()
{
	local	dir_font

	case ${OS_ID} in
		termux) 			dir_font="~/.termux"					;;
		ubuntu|kali|debian)	dir_font="${HOME}/.local/share/fonts"	;;
	esac
	if [ ! -f "${dir_font}/Fira Code Regular Nerd Font Complete Mono.ttf" ]; then
		curl --location "${NERDFONT_LINK}" \
				--progress-bar \
				--output nerdfont.zip
		unzip -o nerdfont.zip -d ${dir_font}
		rm -f nerdfont.zip
	fi
	move_if_file_exist ${DIR_MODULE}/nerdfont/.nerdfont_char ${HOME}/.nerdfont_char
	p_info "you can select your font in the terminal settings"
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "nerdfont/install" ]; then
		source ../run
	else
		source ./run
	fi
	install_nerdfont
fi
