#!/bin/bash

function	install::nerdfont()
{
	local	dir_font

	case ${OS_ID} in
		termux) 			dir_font="${HOME}/.termux"					;;
		ubuntu|kali|debian|arch)	dir_font="${HOME}/.local/share/fonts"	;;
	esac

	[ -f "${dir_font}" ] && rm -f
	[ ! -d "${dir_font}" ] && mkdir -p "${dir_font}"

	if [ ! -f "${dir_font}/Fira Code Regular Nerd Font Complete Mono.ttf" ]; then
		curl --location "${NERDFONT_LINK}" \
				--progress-bar \
				--output nerdfont.zip
		unzip -o nerdfont.zip -d ${dir_font}
		rm -f nerdfont.zip
		[ ${OS_ID} == "termux" ] && termux-reload-settings
	fi
	print::info "you can select your font in the terminal settings"
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../dot
	elif [ "${0}" -ef "nerdfont/install" ]; then
		source ../dot
	else
		source ./dot
	fi
	install::nerdfont
fi
