#!/bin/bash

function	post_install_bash()
{
	p_warn "to make effect you have to source your ${red}~/.bashrc${reset}"
}

function	install_bash()
{
	for file in "${PATH_BASH_FILE_IN[@]}"; do
		move_if_file_exist "${DIR_MODULE}/bash/${file}" ${PATH_BASH_DIR_OUT}
	done
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "bash/install" ]; then
		source ../run
	else
		source ./run
	fi
	install_bash
	post_install_bash
fi
