#!/bin/bash

function install_bashrc()
{
	do_bashrc='1'
	if [ -f ${HOME}/.bashrc ]; then
		ask "file ${HOME}/.bashrc exists, do you wan't to overwrite it " "y"
		[ "$?" == "1" ] || do_bashrc='0'
	fi
	if [ "${do_bashrc}" == "1" ]; then
		cp ${BASHRC_PATH} ${HOME}/.bashrc
	fi
}

function install_bash_aliases()
{
	do_bash_aliases='1'
	if [ -f ${HOME}/.bash_aliases ]; then
		ask "file ${HOME}/.bash_aliases exists, do you wan't to overwrite it " "y"
		[ "$?" == "1" ] || do_bash_aliases='0'
	fi
	if [ "${do_bashrc}" == "1" ]; then
		cp ${BASH_ALIASES_PATH} ${HOME}/.bash_aliases
	fi
}

function install_bash_config()
{
	install_bashrc
	install_bash_aliases
}

if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "bash/install" ]; then
		source installer
	else
		source ../installer
	fi
	install_bash_config
fi
