#!/bin/bash

function	install_bashrc()
{
	local	do_install='1'

	if [ -z "${FORCE_REPLACE}" ] && [ -f ${HOME}/.bashrc ]; then
		ask "file ${HOME}/.bashrc exists, do you wan't to overwrite it " "y"
		if [ "$?" == "0" ]; then
			do_install='0'
			p_done "bashrc configuration skiped." 1
		fi
	fi
	if [ "${do_install}" == "1" ]; then
		cp ${BASHRC_PATH} ${HOME}/.bashrc
		p_done "bashrc configuration done."
	fi
}

function	install_bash_aliases()
{
	local	do_install='1'

	if [ -z "${FORCE_REPLACE}" ] && [ -f ${HOME}/.bash_aliases ]; then
		ask "file ${HOME}/.bash_aliases exists, do you wan't to overwrite it " "y"
		if [ "$?" == "0" ]; then
			do_install='0'
			p_done "bash_aliases configuration skiped." 1
		fi
	fi
	if [ "${do_install}" == "1" ]; then
		cp ${BASH_ALIASES_PATH} ${HOME}/.bash_aliases
		p_done "bash_aliases configuration done."
	fi
}

function	install_bash_config()
{
	install_bashrc
	install_bash_aliases
}

if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "bash/install" ]; then
		source installer
	else
		source ../installer
	fi
	install_bash_config
fi
