#!/bin/bash

function	install_htop()
{
	move_if_file_exist ${PATH_HTOPRC_FILE_IN} ${PATH_HTOPRC_FILE_OUT}
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "htop/install" ]; then
		source ../run
	else
		source ./run
	fi
	install_htop
	post_install_htop
fi
