#!/bin/bash

function	install_gdb()
{
	move_if_file_exist ${PATH_GDBINIT_IN} ${PATH_GDBINIT_OUT}
	[ -f "${HOME}/.gdbinit-gef.py" ] && echo source ~/.gdbinit-gef.py >> ${PATH_GDBINIT_OUT}
}

# if not sourced, BASH_SOURCE keep current file when $0 keep launched file
if [ "${BASH_SOURCE[0]}" -ef "${0}" ]; then
	if [ "${0}" -ef "install" ]; then
		source ../../run
	elif [ "${0}" -ef "gdb/install" ]; then
		source ../run
	else
		source ./run
	fi
	install_gdb
fi
